deepset-ai/deepset-cloud-sdk

deepset_cloud_sdk/service/files_service.py, tests/integration/service/test_integration_files_service.py, tests/unit/service/test_files_service.py
- minor
- add factory method for file services
=> chore: file service factory

deepset_cloud_sdk/api/config.py, deepset_cloud_sdk/api/deepset_cloud_api.py, deepset_cloud_sdk/service/files_service.py, tests/integration/api/test_integration_files.py, tests/integration/api/test_integration_upload_sessions.py, tests/unit/api/test_deepset_cloud_api.py
- fix
- use better factory method
- unit tests
=> refactor: better factory for deepset Cloud APi

deepset_cloud_sdk/__init__.py, deepset_cloud_sdk/workflows/async_client/__init__.py, deepset_cloud_sdk/workflows/sync_client/__init__.py
- hotfix
- import sync client like `from deepset_cloud_sdk.async_client import files` => usage `files.upload_file_paths(..)`
=> feat: better imports for workflows

.pre-commit-config.yaml, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/sync_client/files.py, pyproject.toml, tests/unit/test_cli.py, tests/unit/utils/test_load_configuration.py
- cli for listing files
- cli for listing files
- unit tests
=> feat: listing via cli

deepset_cloud_sdk/cli.py, deepset_cloud_sdk/service/files_service.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, examples/cli/README.md, tests/unit/service/test_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- liisting with generators
- unit tests
=> feat: list files generator

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/api/config.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/s3/upload.py, tests/unit/api/test_deepset_cloud_api.py, tests/unit/test_cli.py
- hotfix
- fix allow url to end with /
=> fix: api ur ending

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/s3/upload.py, tests/integration/service/test_integration_files_service.py, tests/unit/s3/test_upload.py
- hotfix
- validate metada file mapping 
- unit tests  (did not add unit tests for existing not covered lines)
=> feat: validate file meta mappig

deepset_cloud_sdk/s3/upload.py, deepset_cloud_sdk/service/files_service.py
=> chore: add logs for file validations

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/service/files_service.py
=> feat: log line for uploaded all files

README.md, deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/__init__.py, deepset_cloud_sdk/service/files_service.py, examples/sdk/upload.py
- hotfix
- make login explicit for sdk 
- remove default workspace from sdk to use env but keep commented
- make explicit when to use the upload texts 
- add progress bar for waiting for ingestion 
- set debug level to info
- not yet
=> feat: comments from @oryx1729

.github/workflows/continuous-integration.yml, .gitignore, deepset_cloud_sdk/workflows/sync_client/files.py, deepset_cloud_sdk/workflows/sync_client/utils.py, pyproject.toml, tests/unit/workflows/sync_client/test_utils.py
- fixes https://github.com/deepset-ai/deepset-cloud-sdk/issues/36
- introduce util to cleanly iterate over async generator
- adjust project to target lowest compatible version (otherwise we might not catch some issues with older versions)
=> fix: fix StopIteratorException

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/service/files_service.py
=> fix: referenced before assignement

README.md, deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/api/config.py, deepset_cloud_sdk/cli.py, examples/cli/README.md, examples/sdk/upload.py, pyproject.toml
- https://github.com/deepset-ai/deepset-cloud-sdk/issues/53
- rename deepset-cloud-cli script to deepset-cloud
=> chore: renaming

deepset_cloud_sdk/_s3/upload.py
- hotfix
- missing info why a file failed added to the log
=> feat: add exception to log output

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, pyproject.toml
[#3118](https://github.com/deepset-ai/haystack-hub-api/issues/3118)
=> docs: Update reference docs and add missing params

docs/index.md
- hotfix
- link to official docs page
=> fix: link to docs

deepset_cloud_sdk/_s3/upload.py
Sometimes we get a redirect to a different URL from S3 (e.g. the region was added to the URL).
We need to rebuild the file data as FormData does not support multiple requests, for example during automatic redirects. 
See https://github.com/aio-libs/aiohttp/issues/5577
- handle redirects appropriately
- rand our ephemeral environment file uploads
=> fix: S3 redirects

.github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/deploy.yml
I reverted the variable inputs to the how they were on the last working release. From my understanding this shouldn't really make a difference but somehow it does.
ran a deployment: https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/5715912452/job/15486373805
=> fix: deployment configuration variables

README.md
=> Docs: Fix links

README.md, docs/_pydoc/config/async_client.yml, docs/_pydoc/config/cli.yml, docs/_pydoc/config/sync_client.yml, docs/examples/cli/README.md, docs/examples/sdk/README.md, docs/upload_files.md, mkdocs.yml
=> docs: Add metadata info and collab example

docs/_pydoc/requirements.txt
- hotfix
- https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/6073602847/job/16476229224#step:5:116
locally
=> fix: doc generation

docs/examples/cli/README.md, docs/upload_files.md
Feedback from the SOL team.
Added explicit instructions for different OSes + info about folder structure.
=> Docs: Add windows instructions

.github/workflows/continuous-integration.yml, .github/workflows/deploy.yml, .github/workflows/merge-queue.yml
=> feat: use merge queues

tests/integration/service/test_integration_files_service.py
=> fix: missing workspace for read

.github/workflows/continuous-deployment-prod.yml
=> fix: add API variable var

pyproject.toml, tests/conftest.py, tests/integration/api/test_integration_files.py
- tests: use temporary workspace
- tests: use session scoped fixture for speed up
=> tests: use temporary workspace

docs/examples/sdk/upload.py
- fixes #126 
Added missing imports to code samples
=> Fix: Add missing imports to docstrings

.github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, deepset_cloud_sdk/__about__.py
- use hatch auto versions from tag
=> fix: deploy from tag

.github/workflows/deploy.yml
=> fix: don't run CI for publish

.github/workflows/api-docs.yaml, deepset_cloud_sdk/__about__.py
=> feat: build docs

deepset_cloud_sdk/cli.py
=> docs: Update docstrings

deepset_cloud_sdk/_service/files_service.py
- fixes https://deepset.atlassian.net/browse/DC-1045
- no need to warn users about a now non-existing delay 🎉
=> chore: drop warning about delay

deepset_cloud_sdk/_service/files_service.py, tests/unit/service/test_files_service.py
https://deepset.atlassian.net/browse/DC-1120
- fixes #DC-1120
=> fix: exclude directories from path [DC-1120]

deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, docs/examples/cli/README.md, tests/unit/test_cli.py
=> refactor: allow file types in sdk refactor

README.md
=> Docs: Change doc links

pyproject.toml
Loosen the structlog dependency to not interfere with other installations
=>  loosen structlog version dependency

deepset_cloud_sdk/_api/upload_sessions.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/unit/api/test_upload_sessions.py, tests/unit/service/test_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- expose flag from https://github.com/deepset-ai/haystack-hub-api/pull/4638
=> chore: expose parallel processing option

deepset_cloud_sdk/_s3/upload.py
=> chore: delete old warn log

.pre-commit-config.yaml, deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
=> fix: expose error message from payload

deepset_cloud_sdk/_s3/upload.py
=> fix: show reason of upload error

deepset_cloud_sdk/_api/config.py, deepset_cloud_sdk/_api/deepset_cloud_api.py, deepset_cloud_sdk/_s3/upload.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/conftest.py, tests/integration/api/test_integration_upload_sessions.py, tests/integration/service/test_integration_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- fixes https://deepset.atlassian.net/browse/DC-3142
- introduce `--safe-mode` flag
- increases retries
- removes timeouts and concurrency
- extended tests
- all integration tests run in safe-mode as well
=> feat: safe-mode for upload and download

deepset_cloud_sdk/_s3/upload.py
=> fix: error reason on retry

deepset_cloud_sdk/cli.py, tests/unit/test_cli.py
- fixes https://deepset.atlassian.net/browse/DC-3190
add login option to set url to US or custom url
=> feat: add us env

.github/workflows/compliance.yml, .github/workflows/continuous-deployment-dev.yml, .github/workflows/continuous-deployment-prod.yml, .github/workflows/continuous-integration.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/deploy.yml, .github/workflows/merge-queue.yml, CONTRIBUTING.md
=> chore: bump hatch 1.17.0

pyproject.toml
- fixes dependency issues
- weaken pins
=> chore: weaken dependency pins

deepset_cloud_sdk/_service/files_service.py, tests/unit/service/test_files_service.py
=> chore: respect show_progress flag for async file upload

deepset_cloud_sdk/_api/config.py, deepset_cloud_sdk/workflows/pipeline_client/pipeline_service.py, deepset_cloud_sdk/workflows/sdk.py, pyproject.toml, tests/integration/workflows/test_import_into_deepset.py, tests/unit/workflows/pipeline_client/test_pipeline_service.py, tests/unit/workflows/test_sdk.py
- fixes https://deepset.atlassian.net/jira/software/c/projects/DC/boards/11?selectedIssue=DC-4086
- adds explicit init params
- adds integration tests for pipeline import feature
=> feat: add explicit init params to SDK class [DC-4086]
