deepset-ai/deepset-cloud-sdk

.github/workflows/continuous-integration.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/deploy.yml, CONTRIBUTING.md, README.md, pyproject.toml
- related [#2683](https://github.com/deepset-ai/haystack-hub-api/issues/2863)
Adds workflow jobs to publish to PyPi and TestPyPi
https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/4928630145
=> ci: add jobs to publish to PyPi

deepset_cloud_sdk/api/deepset_cloud_api.py, deepset_cloud_sdk/api/upload_sessions.py, deepset_cloud_sdk/models.py, tests/conftest.py, tests/integration/test_integration_files.py, tests/integration/test_integration_upload_sessions.py, tests/unit/api/test_deepset_cloud_api.py, tests/unit/api/test_files.py, tests/unit/api/test_upload_sessions.py
- utilities for creating sessions
- create session 
- close session 
- list session
- get session status
- unit tests
- integration tests
=> feat: create session api

deepset_cloud_sdk/_api/upload_sessions.py, deepset_cloud_sdk/_service/files_service.py, tests/integration/api/test_integration_files.py, tests/integration/api/test_integration_upload_sessions.py, tests/integration/service/test_integration_files_service.py, tests/unit/api/test_files.py, tests/unit/api/test_upload_sessions.py, tests/unit/service/test_files_service.py
- hotfix
- we have seen that the api can sporadically return a 502 if its under load during uploading. So we should add a retry to listing the sessions and fetching the status
- unit tests
=> feat: retry read calls for upload sessions

deepset_cloud_sdk/_api/deepset_cloud_api.py, tests/unit/api/test_deepset_cloud_api.py
Based on https://github.com/deepset-ai/haystack-hub-api/pull/3015 and for https://github.com/deepset-ai/haystack-hub-api/issues/2432.
Adding a header to all request to check in the product metrics where our calls are coming from.
=> feat: set X-Client-Source for product metrics

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/_api/deepset_cloud_api.py, tests/unit/api/test_deepset_cloud_api.py
- hotfix
- add retry for read errors for get requests to deepset cloud api 
- unit tests
=> fix: retry for read error

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/workflows/sync_client/files.py
- hotfix
- delete wrong warning
- not required
=> fix: drop old warning for file limit on workspace

.github/actions/integration_tests/action.yml, .github/workflows/continuous-deployment-dev.yml, .github/workflows/continuous-deployment-prod.yml, .github/workflows/continuous-integration.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/deploy.yml, CONTRIBUTING.md
**The CI/CD flow is updated as follows:**
Code quality checks, unit tests, and integration tests (against dev) are performed on the creation of a PR, and subsequent pushes for that PR.
Code quality checks, unit tests, and integration tests (against dev) are performed on a push to main.
Code quality checks, unit tests, and integration tests (against prod) are performed on the publishing of a release tag.
set API_URL for dev in push dispatch for workflow
https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/5339520410/jobs/9678301125
=> ci: publish only on release tag publish + streamline workflow triggering

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
- hotfix
- add exception to logger 
- added exception to upload summary 
- adjusted test
=> feat: error message for failed upload

deepset_cloud_sdk/__about__.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/integration/service/test_integration_files_service.py, tests/unit/service/test_files_service.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- fixes https://github.com/deepset-ai/deepset-cloud-sdk/issues/102
- return upload session summary
- delete legacy upload paths method. We should use `upload` instead 
- fix tests that are not run by accident
=> feat: return upload summary

deepset_cloud_sdk/_api/files.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, docs/examples/cli/README.md, pyproject.toml, tests/integration/service/test_integration_files_service.py, tests/unit/api/test_files.py, tests/unit/service/test_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- fixes https://github.com/deepset-ai/deepset-cloud-sdk/issues/87
- download files from a workspace 
example usage: 
```
deepset-cloud download --workspace-name <your-workspace-name> --file-dir ./<your-folde>
```
cc @sjrl
=> feat: download files

deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- hotfix
- disable timeout. By default don't cancel running processes for uploads
Existing tests.
Users are currently reporting many timeouts that are expected. Since this timeout seems like an issue to users we should keep it open. Large sessions are expected to take longer than the default timeout.
=> fix: disable timeouts

deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
- part 2 of https://github.com/deepset-ai/deepset-cloud-sdk/issues/114
`FormData` is already encoding stuff. No need to do it twice.
=> fix: drop double encoding

.github/actions/integration_tests/action.yml, .github/workflows/deploy-test.yml, .github/workflows/merge-queue.yml, tests/conftest.py, tests/integration/api/test_integration_files.py, tests/integration/api/test_integration_upload_sessions.py, tests/integration/service/test_integration_files_service.py
- no
- run tests on new workspace
- running the CI 
- We still have the 403 bug after creating a workspace.  Once this is fixed this will work too
- https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/6781847627/job/18432902291?pr=129
=> feat: dynamically add workspaces in action

tests/conftest.py, tests/integration/api/test_integration_files.py
- upload enough files to satisfy `test_list_all_files` test
=> tests: upload more files

tests/integration/api/test_integration_upload_sessions.py
remove the assert for has_more for upload sessions list. This is already tested at unit level, but causes flakiness when run in CI due to all the tests running in the same workspace. sometimes other tests run before this one, which create upload sessions, and sometimes they don't, which results in flakiness.
ran the suite locally 5 times with no flakiness
=> fix: flaky upload session integration test

tests/conftest.py
=> fix: use a unique prefix for sdk test workspaces

tests/conftest.py
- fixes workspace not being deleted after failed test which causes workspace congestion in our e2e org.
- See https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/7017651743/job/19091373476
=> fix: workspace not deleted after failed test

deepset_cloud_sdk/_api/files.py, deepset_cloud_sdk/_api/upload_sessions.py, deepset_cloud_sdk/_utils/datetime.py, tests/unit/api/test_upload_sessions.py, tests/unit/utils/test_datetime_utils.py
- fixes https://deepset.atlassian.net/browse/DC-677
- allow parsing timestamps in both formats
- added unit tests
see details in issue
=> fix: timestamp parsing

tests/unit/service/test_files_service.py
- fixes #DC-1120
After pulling the changes of https://github.com/deepset-ai/deepset-cloud-sdk/pull/173/files , the file age had changed locally on my machine and the tests failed. I made the test independent of the actual file age, so we don't rely on the actual files in the file system .
=>  Fix: mock file age in remove_duplicates test [DC-1120]

deepset_cloud_sdk/_service/files_service.py, tests/integration/service/test_integration_files_service.py, tests/test_data/multiple_file_types/file00.txt, tests/test_data/multiple_file_types/file00.txt.meta.json, tests/test_data/multiple_file_types_caps/File00.txt, tests/test_data/multiple_file_types_caps/File00.txt.meta.json, tests/unit/service/test_files_service.py
- fixes https://github.com/deepset-ai/deepset-cloud-sdk/issues/184
- dont run lowercase comparison for metadata matching 
- integration tests 
- we will skip files with capital suffixes as file types from now on
=> fix: lower file type comparison

deepset_cloud_sdk/cli.py
- fixes docs: https://deepset.atlassian.net/browse/DC-1128
- explalin how to use bool values
=> docs: explain how to use boolean or list values

deepset_cloud_sdk/_service/files_service.py, tests/unit/service/test_files_service.py
- fixes https://deepset.atlassian.net/browse/DC-1125
- pass name, content and odata_filters to paginated list to calculate the total filtered files
- existing tests
=> fix: total filtered download

.github/utils/add-category-id.py, .github/workflows/api-docs.yaml
- https://deepset.atlassian.net/browse/DC-1061
- push to readme 
- successful run: https://github.com/deepset-ai/deepset-cloud-sdk/actions/runs/8969098557/job/24629839337
results can be found here: https://docs.cloud.deepset.ai/reference/async_client
=> feat: publish to readme

deepset_cloud_sdk/workflows/async_client/files.py
=> Docs: Fix upload_bytes docstrings

deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py
SOLs suggested upload_bytes() is the method we should promote in the guides, since they can use it for all file types, not just text. I'm deleting upload_texts() examples from https://docs.cloud.deepset.ai/docs/upload-files-with-python#upload-texts-or-bytes and moving them to reference. The how-tos will just have examples of upload_bytes.
I'm not sure the formatting is OK.
=> Docs: Move tupload_texts() example from guides to reference

deepset_cloud_sdk/_api/files.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, pyproject.toml, tests/conftest.py, tests/integration/api/test_integration_files.py, tests/unit/api/test_files.py, tests/unit/service/test_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- deprecate content filter
- deprecate not longer supported and not used content filter
- fix integration tests
=> chore: drop content filter

deepset_cloud_sdk/_api/config.py, deepset_cloud_sdk/_api/deepset_cloud_api.py, deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
- fixes minor reliability issues
- make async client timeout configurable via `ASYNC_CLIENT_TIMEOUT` env variable (default of 5 mins is quite small)
- retry session close requests in case of httpx.ConnectErrors
- increase retry attempts for file upload requests from 3 to 5
- retry file uploads on `aiohttp.ClientConnectionErrors`
=> fix: minor reliability improvements

deepset_cloud_sdk/_api/deepset_cloud_api.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
Uses the constant `SUPPORTED_TYPE_SUFFIXES` every where relevant. Originally missed in some places when adding new file type support to dC.
=> chore: Make all supported file types default everywhere

deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
=> fix: support s3 xml error messages

deepset_cloud_sdk/_s3/upload.py, tests/unit/s3/test_upload.py
=> fix: retry s3 HTTP 400

deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py
=> Docs: Update safe mode description

README.md
=> fix: markdown link

deepset_cloud_sdk/_api/files.py, deepset_cloud_sdk/_service/files_service.py, deepset_cloud_sdk/_utils/constants.py, deepset_cloud_sdk/cli.py, deepset_cloud_sdk/workflows/async_client/files.py, deepset_cloud_sdk/workflows/sync_client/files.py, tests/integration/service/test_integration_files_service.py, tests/unit/api/test_files.py, tests/unit/service/test_files_service.py, tests/unit/test_cli.py, tests/unit/workflows/async_client/test_async_workflow_files.py, tests/unit/workflows/sync_client/test_sync_workflow_files.py
- https://deepset.atlassian.net/browse/DC-3508
This pull request removes the `SUPPORTED_TYPE_SUFFIXES` constant and updates the codebase to handle file type validation differently. The changes focus on simplifying the file upload process and removing redundant checks.
* [`deepset_cloud_sdk/_api/files.py`](diffhunk://#diff-2917862807c8abbfbb07f4df690dc9c01ac93236e9ce9ff73d3dc7b98133f3a7L21): Removed the `SUPPORTED_TYPE_SUFFIXES` import and the file type validation check in `direct_upload_in_memory`. [[1]](diffhunk://#diff-2917862807c8abbfbb07f4df690dc9c01ac93236e9ce9ff73d3dc7b98133f3a7L21) [[2]](diffhunk://#diff-2917862807c8abbfbb07f4df690dc9c01ac93236e9ce9ff73d3dc7b98133f3a7L228-L233)
* [`deepset_cloud_sdk/_service/files_service.py`](diffhunk://#diff-7b64b0883c287e8f6400a4c5d16368736cfb1f4 …
=> feat: drop file type restriction for upload

deepset_cloud_sdk/_s3/upload.py
- fixes limiter leaking 3 file descriptors per `upload` call
- manually release resources of limiter
- ran test script simulating a real world upload usage having multiple `asyncio.run(upload)` invocations
=> fix: limiter leaking filedescriptors

deepset_cloud_sdk/_s3/upload.py, pyproject.toml
- old versions of pyrate limiter breaking disposing buckets (see comments in code)
=> fix: buckets attribute

deepset_cloud_sdk/__init__.py, deepset_cloud_sdk/workflows/__init__.py, deepset_cloud_sdk/workflows/pipeline_client/__init__.py, deepset_cloud_sdk/workflows/pipeline_client/pipeline_service.py, tests/integration/workflows/test_integration_pipeline_client.py, tests/unit/workflows/pipeline_client/test_pipeline_service.py
- when overwriting existing pipelines, the validation would always warn about pipeline/index already existing
- Fixed by excluding the name from the validation call in case of overwrite
- Fixes import of PipelineOutputType
=> fix: do not validate name if overwrite set to true
